project:
  type: website

website:
  title: "Eduardo Lima"
  navbar:
    left:
      - text: Home
        href: index.qmd
      - text: Blog
        href: posts/
      - text: About
        href: about.qmd

format:
  html:
    theme: flatly
    toc: true
