project:
  type: website

website:
  title: "Eduardo P. Lima"
  navbar:
    search: true
    left:
      - text: Home
        href: index.qmd
      - text: About
        href: about.qmd

format:
  html:
    theme: flatly
    toc: true
